// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package transaction

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (user_id, amount, transaction_type, description, category, transaction_date, wallet_id)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, user_id, amount, transaction_type, description, category, transaction_date, wallet_id, created_at
`

type CreateTransactionParams struct {
	UserID          pgtype.UUID        `json:"user_id"`
	Amount          int64              `json:"amount"`
	TransactionType string             `json:"transaction_type"`
	Description     pgtype.Text        `json:"description"`
	Category        string             `json:"category"`
	TransactionDate pgtype.Timestamptz `json:"transaction_date"`
	WalletID        pgtype.UUID        `json:"wallet_id"`
}

type CreateTransactionRow struct {
	ID              pgtype.UUID        `json:"id"`
	UserID          pgtype.UUID        `json:"user_id"`
	Amount          int64              `json:"amount"`
	TransactionType string             `json:"transaction_type"`
	Description     pgtype.Text        `json:"description"`
	Category        string             `json:"category"`
	TransactionDate pgtype.Timestamptz `json:"transaction_date"`
	WalletID        pgtype.UUID        `json:"wallet_id"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (CreateTransactionRow, error) {
	row := q.db.QueryRow(ctx, createTransaction,
		arg.UserID,
		arg.Amount,
		arg.TransactionType,
		arg.Description,
		arg.Category,
		arg.TransactionDate,
		arg.WalletID,
	)
	var i CreateTransactionRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Amount,
		&i.TransactionType,
		&i.Description,
		&i.Category,
		&i.TransactionDate,
		&i.WalletID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteTransaction = `-- name: DeleteTransaction :exec
DELETE FROM transactions
WHERE id = $1 AND user_id = $2
`

type DeleteTransactionParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) DeleteTransaction(ctx context.Context, arg DeleteTransactionParams) error {
	_, err := q.db.Exec(ctx, deleteTransaction, arg.ID, arg.UserID)
	return err
}

const getMonthlyTotal = `-- name: GetMonthlyTotal :many
SELECT transaction_type, COALESCE(SUM(amount), 0)::BIGINT AS total
FROM transactions
WHERE user_id = $1
  AND transaction_date >= $2
  AND transaction_date < $3
GROUP BY transaction_type
`

type GetMonthlyTotalParams struct {
	UserID            pgtype.UUID        `json:"user_id"`
	TransactionDate   pgtype.Timestamptz `json:"transaction_date"`
	TransactionDate_2 pgtype.Timestamptz `json:"transaction_date_2"`
}

type GetMonthlyTotalRow struct {
	TransactionType string `json:"transaction_type"`
	Total           int64  `json:"total"`
}

func (q *Queries) GetMonthlyTotal(ctx context.Context, arg GetMonthlyTotalParams) ([]GetMonthlyTotalRow, error) {
	rows, err := q.db.Query(ctx, getMonthlyTotal, arg.UserID, arg.TransactionDate, arg.TransactionDate_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMonthlyTotalRow
	for rows.Next() {
		var i GetMonthlyTotalRow
		if err := rows.Scan(&i.TransactionType, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTransactionByID = `-- name: GetTransactionByID :one
SELECT t.id, t.user_id, t.amount, t.transaction_type, t.description, t.category, t.transaction_date, t.wallet_id, t.created_at, COALESCE(w.name, '') AS wallet_name
FROM transactions t
LEFT JOIN wallets w ON t.wallet_id = w.id
WHERE t.id = $1 AND t.user_id = $2
`

type GetTransactionByIDParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

type GetTransactionByIDRow struct {
	ID              pgtype.UUID        `json:"id"`
	UserID          pgtype.UUID        `json:"user_id"`
	Amount          int64              `json:"amount"`
	TransactionType string             `json:"transaction_type"`
	Description     pgtype.Text        `json:"description"`
	Category        string             `json:"category"`
	TransactionDate pgtype.Timestamptz `json:"transaction_date"`
	WalletID        pgtype.UUID        `json:"wallet_id"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	WalletName      string             `json:"wallet_name"`
}

func (q *Queries) GetTransactionByID(ctx context.Context, arg GetTransactionByIDParams) (GetTransactionByIDRow, error) {
	row := q.db.QueryRow(ctx, getTransactionByID, arg.ID, arg.UserID)
	var i GetTransactionByIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Amount,
		&i.TransactionType,
		&i.Description,
		&i.Category,
		&i.TransactionDate,
		&i.WalletID,
		&i.CreatedAt,
		&i.WalletName,
	)
	return i, err
}

const listTransactionsByUser = `-- name: ListTransactionsByUser :many
SELECT t.id, t.user_id, t.amount, t.transaction_type, t.description, t.category, t.transaction_date, t.wallet_id, t.created_at, COALESCE(w.name, '') AS wallet_name
FROM transactions t
LEFT JOIN wallets w ON t.wallet_id = w.id
WHERE t.user_id = $1
ORDER BY t.transaction_date DESC, t.created_at DESC
LIMIT $2 OFFSET $3
`

type ListTransactionsByUserParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

type ListTransactionsByUserRow struct {
	ID              pgtype.UUID        `json:"id"`
	UserID          pgtype.UUID        `json:"user_id"`
	Amount          int64              `json:"amount"`
	TransactionType string             `json:"transaction_type"`
	Description     pgtype.Text        `json:"description"`
	Category        string             `json:"category"`
	TransactionDate pgtype.Timestamptz `json:"transaction_date"`
	WalletID        pgtype.UUID        `json:"wallet_id"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	WalletName      string             `json:"wallet_name"`
}

func (q *Queries) ListTransactionsByUser(ctx context.Context, arg ListTransactionsByUserParams) ([]ListTransactionsByUserRow, error) {
	rows, err := q.db.Query(ctx, listTransactionsByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTransactionsByUserRow
	for rows.Next() {
		var i ListTransactionsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Amount,
			&i.TransactionType,
			&i.Description,
			&i.Category,
			&i.TransactionDate,
			&i.WalletID,
			&i.CreatedAt,
			&i.WalletName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionsByUserAndType = `-- name: ListTransactionsByUserAndType :many
SELECT t.id, t.user_id, t.amount, t.transaction_type, t.description, t.category, t.transaction_date, t.wallet_id, t.created_at, COALESCE(w.name, '') AS wallet_name
FROM transactions t
LEFT JOIN wallets w ON t.wallet_id = w.id
WHERE t.user_id = $1 AND t.transaction_type = $2
ORDER BY t.transaction_date DESC, t.created_at DESC
LIMIT $3 OFFSET $4
`

type ListTransactionsByUserAndTypeParams struct {
	UserID          pgtype.UUID `json:"user_id"`
	TransactionType string      `json:"transaction_type"`
	Limit           int32       `json:"limit"`
	Offset          int32       `json:"offset"`
}

type ListTransactionsByUserAndTypeRow struct {
	ID              pgtype.UUID        `json:"id"`
	UserID          pgtype.UUID        `json:"user_id"`
	Amount          int64              `json:"amount"`
	TransactionType string             `json:"transaction_type"`
	Description     pgtype.Text        `json:"description"`
	Category        string             `json:"category"`
	TransactionDate pgtype.Timestamptz `json:"transaction_date"`
	WalletID        pgtype.UUID        `json:"wallet_id"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	WalletName      string             `json:"wallet_name"`
}

func (q *Queries) ListTransactionsByUserAndType(ctx context.Context, arg ListTransactionsByUserAndTypeParams) ([]ListTransactionsByUserAndTypeRow, error) {
	rows, err := q.db.Query(ctx, listTransactionsByUserAndType,
		arg.UserID,
		arg.TransactionType,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTransactionsByUserAndTypeRow
	for rows.Next() {
		var i ListTransactionsByUserAndTypeRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Amount,
			&i.TransactionType,
			&i.Description,
			&i.Category,
			&i.TransactionDate,
			&i.WalletID,
			&i.CreatedAt,
			&i.WalletName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTransaction = `-- name: UpdateTransaction :one
UPDATE transactions
SET amount = $3, transaction_type = $4, description = $5, category = $6, transaction_date = $7, wallet_id = $8
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, amount, transaction_type, description, category, transaction_date, wallet_id, created_at
`

type UpdateTransactionParams struct {
	ID              pgtype.UUID        `json:"id"`
	UserID          pgtype.UUID        `json:"user_id"`
	Amount          int64              `json:"amount"`
	TransactionType string             `json:"transaction_type"`
	Description     pgtype.Text        `json:"description"`
	Category        string             `json:"category"`
	TransactionDate pgtype.Timestamptz `json:"transaction_date"`
	WalletID        pgtype.UUID        `json:"wallet_id"`
}

type UpdateTransactionRow struct {
	ID              pgtype.UUID        `json:"id"`
	UserID          pgtype.UUID        `json:"user_id"`
	Amount          int64              `json:"amount"`
	TransactionType string             `json:"transaction_type"`
	Description     pgtype.Text        `json:"description"`
	Category        string             `json:"category"`
	TransactionDate pgtype.Timestamptz `json:"transaction_date"`
	WalletID        pgtype.UUID        `json:"wallet_id"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) UpdateTransaction(ctx context.Context, arg UpdateTransactionParams) (UpdateTransactionRow, error) {
	row := q.db.QueryRow(ctx, updateTransaction,
		arg.ID,
		arg.UserID,
		arg.Amount,
		arg.TransactionType,
		arg.Description,
		arg.Category,
		arg.TransactionDate,
		arg.WalletID,
	)
	var i UpdateTransactionRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Amount,
		&i.TransactionType,
		&i.Description,
		&i.Category,
		&i.TransactionDate,
		&i.WalletID,
		&i.CreatedAt,
	)
	return i, err
}
