// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package admin

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveUsers = `-- name: CountActiveUsers :one
SELECT COUNT(DISTINCT user_id)::BIGINT AS total
FROM transactions
WHERE transaction_date >= CURRENT_DATE - INTERVAL '7 days'
`

func (q *Queries) CountActiveUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveUsers)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const countTelegramUsers = `-- name: CountTelegramUsers :one
SELECT COUNT(*)::BIGINT AS total FROM users WHERE telegram_id IS NOT NULL AND telegram_id != ''
`

func (q *Queries) CountTelegramUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countTelegramUsers)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const countTransactions = `-- name: CountTransactions :one
SELECT COUNT(*)::BIGINT AS total FROM transactions
`

func (q *Queries) CountTransactions(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countTransactions)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*)::BIGINT AS total FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const getDatabaseSize = `-- name: GetDatabaseSize :one
SELECT pg_size_pretty(pg_database_size(current_database())) AS db_size
`

func (q *Queries) GetDatabaseSize(ctx context.Context) (string, error) {
	row := q.db.QueryRow(ctx, getDatabaseSize)
	var db_size string
	err := row.Scan(&db_size)
	return db_size, err
}

const listAllUsers = `-- name: ListAllUsers :many
SELECT u.id, u.email, u.name, u.telegram_id, u.created_at,
       COUNT(t.id)::BIGINT AS tx_count
FROM users u
LEFT JOIN transactions t ON t.user_id = u.id
GROUP BY u.id, u.email, u.name, u.telegram_id, u.created_at
ORDER BY u.created_at DESC
`

type ListAllUsersRow struct {
	ID         pgtype.UUID        `json:"id"`
	Email      string             `json:"email"`
	Name       string             `json:"name"`
	TelegramID pgtype.Int8        `json:"telegram_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	TxCount    int64              `json:"tx_count"`
}

func (q *Queries) ListAllUsers(ctx context.Context) ([]ListAllUsersRow, error) {
	rows, err := q.db.Query(ctx, listAllUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllUsersRow
	for rows.Next() {
		var i ListAllUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.TelegramID,
			&i.CreatedAt,
			&i.TxCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const newUsersToday = `-- name: NewUsersToday :one
SELECT COUNT(*)::BIGINT AS total FROM users WHERE created_at::date = CURRENT_DATE
`

func (q *Queries) NewUsersToday(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, newUsersToday)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const recentTransactions = `-- name: RecentTransactions :many
SELECT t.id, t.amount, t.transaction_type, t.description, t.category, t.transaction_date, t.created_at,
       u.name AS user_name, u.email AS user_email
FROM transactions t
JOIN users u ON u.id = t.user_id
ORDER BY t.created_at DESC
LIMIT 10
`

type RecentTransactionsRow struct {
	ID              pgtype.UUID        `json:"id"`
	Amount          int64              `json:"amount"`
	TransactionType string             `json:"transaction_type"`
	Description     pgtype.Text        `json:"description"`
	Category        string             `json:"category"`
	TransactionDate pgtype.Timestamptz `json:"transaction_date"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UserName        string             `json:"user_name"`
	UserEmail       string             `json:"user_email"`
}

func (q *Queries) RecentTransactions(ctx context.Context) ([]RecentTransactionsRow, error) {
	rows, err := q.db.Query(ctx, recentTransactions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RecentTransactionsRow
	for rows.Next() {
		var i RecentTransactionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Amount,
			&i.TransactionType,
			&i.Description,
			&i.Category,
			&i.TransactionDate,
			&i.CreatedAt,
			&i.UserName,
			&i.UserEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const topCategories = `-- name: TopCategories :many
SELECT category, COUNT(*)::BIGINT AS tx_count, COALESCE(SUM(amount), 0)::BIGINT AS total_amount
FROM transactions
GROUP BY category
ORDER BY tx_count DESC
LIMIT 5
`

type TopCategoriesRow struct {
	Category    string `json:"category"`
	TxCount     int64  `json:"tx_count"`
	TotalAmount int64  `json:"total_amount"`
}

func (q *Queries) TopCategories(ctx context.Context) ([]TopCategoriesRow, error) {
	rows, err := q.db.Query(ctx, topCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TopCategoriesRow
	for rows.Next() {
		var i TopCategoriesRow
		if err := rows.Scan(&i.Category, &i.TxCount, &i.TotalAmount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const totalExpense = `-- name: TotalExpense :one
SELECT COALESCE(SUM(amount), 0)::BIGINT AS total FROM transactions WHERE transaction_type = 'EXPENSE'
`

func (q *Queries) TotalExpense(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, totalExpense)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const totalIncome = `-- name: TotalIncome :one
SELECT COALESCE(SUM(amount), 0)::BIGINT AS total FROM transactions WHERE transaction_type = 'INCOME'
`

func (q *Queries) TotalIncome(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, totalIncome)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const totalVolume = `-- name: TotalVolume :one
SELECT COALESCE(SUM(amount), 0)::BIGINT AS total FROM transactions
`

func (q *Queries) TotalVolume(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, totalVolume)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const transactionsToday = `-- name: TransactionsToday :one
SELECT COUNT(*)::BIGINT AS total FROM transactions WHERE transaction_date = CURRENT_DATE
`

func (q *Queries) TransactionsToday(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, transactionsToday)
	var total int64
	err := row.Scan(&total)
	return total, err
}
