// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package recurring

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRecurring = `-- name: CreateRecurring :one
INSERT INTO recurring_transactions (user_id, amount, transaction_type, description, category, wallet_id, frequency, next_run)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, user_id, amount, transaction_type, description, category, wallet_id, frequency, next_run, is_active, created_at
`

type CreateRecurringParams struct {
	UserID          pgtype.UUID `json:"user_id"`
	Amount          int64       `json:"amount"`
	TransactionType string      `json:"transaction_type"`
	Description     string      `json:"description"`
	Category        string      `json:"category"`
	WalletID        pgtype.UUID `json:"wallet_id"`
	Frequency       string      `json:"frequency"`
	NextRun         pgtype.Date `json:"next_run"`
}

func (q *Queries) CreateRecurring(ctx context.Context, arg CreateRecurringParams) (RecurringTransaction, error) {
	row := q.db.QueryRow(ctx, createRecurring,
		arg.UserID,
		arg.Amount,
		arg.TransactionType,
		arg.Description,
		arg.Category,
		arg.WalletID,
		arg.Frequency,
		arg.NextRun,
	)
	var i RecurringTransaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Amount,
		&i.TransactionType,
		&i.Description,
		&i.Category,
		&i.WalletID,
		&i.Frequency,
		&i.NextRun,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const deleteRecurring = `-- name: DeleteRecurring :exec
DELETE FROM recurring_transactions
WHERE id = $1 AND user_id = $2
`

type DeleteRecurringParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) DeleteRecurring(ctx context.Context, arg DeleteRecurringParams) error {
	_, err := q.db.Exec(ctx, deleteRecurring, arg.ID, arg.UserID)
	return err
}

const listDueRecurring = `-- name: ListDueRecurring :many
SELECT r.id, r.user_id, r.amount, r.transaction_type, r.description, r.category, r.wallet_id, r.frequency, r.next_run, r.is_active, r.created_at
FROM recurring_transactions r
WHERE r.is_active = true AND r.next_run <= $1
`

func (q *Queries) ListDueRecurring(ctx context.Context, nextRun pgtype.Date) ([]RecurringTransaction, error) {
	rows, err := q.db.Query(ctx, listDueRecurring, nextRun)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RecurringTransaction
	for rows.Next() {
		var i RecurringTransaction
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Amount,
			&i.TransactionType,
			&i.Description,
			&i.Category,
			&i.WalletID,
			&i.Frequency,
			&i.NextRun,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecurringByUser = `-- name: ListRecurringByUser :many
SELECT r.id, r.user_id, r.amount, r.transaction_type, r.description, r.category, r.wallet_id, r.frequency, r.next_run, r.is_active, r.created_at, COALESCE(w.name, '') AS wallet_name
FROM recurring_transactions r
LEFT JOIN wallets w ON r.wallet_id = w.id
WHERE r.user_id = $1
ORDER BY r.is_active DESC, r.next_run ASC
`

type ListRecurringByUserRow struct {
	ID              pgtype.UUID        `json:"id"`
	UserID          pgtype.UUID        `json:"user_id"`
	Amount          int64              `json:"amount"`
	TransactionType string             `json:"transaction_type"`
	Description     string             `json:"description"`
	Category        string             `json:"category"`
	WalletID        pgtype.UUID        `json:"wallet_id"`
	Frequency       string             `json:"frequency"`
	NextRun         pgtype.Date        `json:"next_run"`
	IsActive        bool               `json:"is_active"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	WalletName      string             `json:"wallet_name"`
}

func (q *Queries) ListRecurringByUser(ctx context.Context, userID pgtype.UUID) ([]ListRecurringByUserRow, error) {
	rows, err := q.db.Query(ctx, listRecurringByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRecurringByUserRow
	for rows.Next() {
		var i ListRecurringByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Amount,
			&i.TransactionType,
			&i.Description,
			&i.Category,
			&i.WalletID,
			&i.Frequency,
			&i.NextRun,
			&i.IsActive,
			&i.CreatedAt,
			&i.WalletName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const toggleRecurring = `-- name: ToggleRecurring :one
UPDATE recurring_transactions
SET is_active = NOT is_active
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, amount, transaction_type, description, category, wallet_id, frequency, next_run, is_active, created_at
`

type ToggleRecurringParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) ToggleRecurring(ctx context.Context, arg ToggleRecurringParams) (RecurringTransaction, error) {
	row := q.db.QueryRow(ctx, toggleRecurring, arg.ID, arg.UserID)
	var i RecurringTransaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Amount,
		&i.TransactionType,
		&i.Description,
		&i.Category,
		&i.WalletID,
		&i.Frequency,
		&i.NextRun,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const updateNextRun = `-- name: UpdateNextRun :exec
UPDATE recurring_transactions
SET next_run = $2
WHERE id = $1
`

type UpdateNextRunParams struct {
	ID      pgtype.UUID `json:"id"`
	NextRun pgtype.Date `json:"next_run"`
}

func (q *Queries) UpdateNextRun(ctx context.Context, arg UpdateNextRunParams) error {
	_, err := q.db.Exec(ctx, updateNextRun, arg.ID, arg.NextRun)
	return err
}

const updateRecurring = `-- name: UpdateRecurring :one
UPDATE recurring_transactions
SET amount = $3, transaction_type = $4, description = $5, category = $6, wallet_id = $7, frequency = $8, next_run = $9, is_active = $10
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, amount, transaction_type, description, category, wallet_id, frequency, next_run, is_active, created_at
`

type UpdateRecurringParams struct {
	ID              pgtype.UUID `json:"id"`
	UserID          pgtype.UUID `json:"user_id"`
	Amount          int64       `json:"amount"`
	TransactionType string      `json:"transaction_type"`
	Description     string      `json:"description"`
	Category        string      `json:"category"`
	WalletID        pgtype.UUID `json:"wallet_id"`
	Frequency       string      `json:"frequency"`
	NextRun         pgtype.Date `json:"next_run"`
	IsActive        bool        `json:"is_active"`
}

func (q *Queries) UpdateRecurring(ctx context.Context, arg UpdateRecurringParams) (RecurringTransaction, error) {
	row := q.db.QueryRow(ctx, updateRecurring,
		arg.ID,
		arg.UserID,
		arg.Amount,
		arg.TransactionType,
		arg.Description,
		arg.Category,
		arg.WalletID,
		arg.Frequency,
		arg.NextRun,
		arg.IsActive,
	)
	var i RecurringTransaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Amount,
		&i.TransactionType,
		&i.Description,
		&i.Category,
		&i.WalletID,
		&i.Frequency,
		&i.NextRun,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}
