// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package tripay

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPaymentOrder = `-- name: CreatePaymentOrder :one
INSERT INTO payment_orders (user_id, tripay_reference, merchant_ref, method, amount, status, checkout_url, pay_code, expired_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, user_id, tripay_reference, merchant_ref, method, amount, status, checkout_url, pay_code, expired_at, paid_at, created_at
`

type CreatePaymentOrderParams struct {
	UserID          pgtype.UUID        `json:"user_id"`
	TripayReference pgtype.Text        `json:"tripay_reference"`
	MerchantRef     string             `json:"merchant_ref"`
	Method          string             `json:"method"`
	Amount          int32              `json:"amount"`
	Status          string             `json:"status"`
	CheckoutUrl     pgtype.Text        `json:"checkout_url"`
	PayCode         pgtype.Text        `json:"pay_code"`
	ExpiredAt       pgtype.Timestamptz `json:"expired_at"`
}

func (q *Queries) CreatePaymentOrder(ctx context.Context, arg CreatePaymentOrderParams) (PaymentOrder, error) {
	row := q.db.QueryRow(ctx, createPaymentOrder,
		arg.UserID,
		arg.TripayReference,
		arg.MerchantRef,
		arg.Method,
		arg.Amount,
		arg.Status,
		arg.CheckoutUrl,
		arg.PayCode,
		arg.ExpiredAt,
	)
	var i PaymentOrder
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TripayReference,
		&i.MerchantRef,
		&i.Method,
		&i.Amount,
		&i.Status,
		&i.CheckoutUrl,
		&i.PayCode,
		&i.ExpiredAt,
		&i.PaidAt,
		&i.CreatedAt,
	)
	return i, err
}

const getLatestPendingOrder = `-- name: GetLatestPendingOrder :one
SELECT id, user_id, tripay_reference, merchant_ref, method, amount, status, checkout_url, pay_code, expired_at, paid_at, created_at
FROM payment_orders
WHERE user_id = $1 AND status = 'UNPAID' AND expired_at > NOW()
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetLatestPendingOrder(ctx context.Context, userID pgtype.UUID) (PaymentOrder, error) {
	row := q.db.QueryRow(ctx, getLatestPendingOrder, userID)
	var i PaymentOrder
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TripayReference,
		&i.MerchantRef,
		&i.Method,
		&i.Amount,
		&i.Status,
		&i.CheckoutUrl,
		&i.PayCode,
		&i.ExpiredAt,
		&i.PaidAt,
		&i.CreatedAt,
	)
	return i, err
}

const getPaymentOrderByMerchantRef = `-- name: GetPaymentOrderByMerchantRef :one
SELECT id, user_id, tripay_reference, merchant_ref, method, amount, status, checkout_url, pay_code, expired_at, paid_at, created_at
FROM payment_orders
WHERE merchant_ref = $1
`

func (q *Queries) GetPaymentOrderByMerchantRef(ctx context.Context, merchantRef string) (PaymentOrder, error) {
	row := q.db.QueryRow(ctx, getPaymentOrderByMerchantRef, merchantRef)
	var i PaymentOrder
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TripayReference,
		&i.MerchantRef,
		&i.Method,
		&i.Amount,
		&i.Status,
		&i.CheckoutUrl,
		&i.PayCode,
		&i.ExpiredAt,
		&i.PaidAt,
		&i.CreatedAt,
	)
	return i, err
}

const updatePaymentOrderStatus = `-- name: UpdatePaymentOrderStatus :exec
UPDATE payment_orders
SET status = $2, paid_at = $3, tripay_reference = $4
WHERE merchant_ref = $1
`

type UpdatePaymentOrderStatusParams struct {
	MerchantRef     string             `json:"merchant_ref"`
	Status          string             `json:"status"`
	PaidAt          pgtype.Timestamptz `json:"paid_at"`
	TripayReference pgtype.Text        `json:"tripay_reference"`
}

func (q *Queries) UpdatePaymentOrderStatus(ctx context.Context, arg UpdatePaymentOrderStatusParams) error {
	_, err := q.db.Exec(ctx, updatePaymentOrderStatus,
		arg.MerchantRef,
		arg.Status,
		arg.PaidAt,
		arg.TripayReference,
	)
	return err
}
