// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package wallet

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createWallet = `-- name: CreateWallet :one
INSERT INTO wallets (user_id, name, icon)
VALUES ($1, $2, $3)
RETURNING id, user_id, name, icon, balance, created_at
`

type CreateWalletParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Name   string      `json:"name"`
	Icon   string      `json:"icon"`
}

func (q *Queries) CreateWallet(ctx context.Context, arg CreateWalletParams) (Wallet, error) {
	row := q.db.QueryRow(ctx, createWallet, arg.UserID, arg.Name, arg.Icon)
	var i Wallet
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Icon,
		&i.Balance,
		&i.CreatedAt,
	)
	return i, err
}

const deleteWallet = `-- name: DeleteWallet :exec
DELETE FROM wallets
WHERE id = $1 AND user_id = $2
`

type DeleteWalletParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) DeleteWallet(ctx context.Context, arg DeleteWalletParams) error {
	_, err := q.db.Exec(ctx, deleteWallet, arg.ID, arg.UserID)
	return err
}

const getWalletByID = `-- name: GetWalletByID :one
SELECT id, user_id, name, icon, balance, created_at
FROM wallets
WHERE id = $1 AND user_id = $2
`

type GetWalletByIDParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetWalletByID(ctx context.Context, arg GetWalletByIDParams) (Wallet, error) {
	row := q.db.QueryRow(ctx, getWalletByID, arg.ID, arg.UserID)
	var i Wallet
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Icon,
		&i.Balance,
		&i.CreatedAt,
	)
	return i, err
}

const getWalletsTotalBalance = `-- name: GetWalletsTotalBalance :one
SELECT COALESCE(SUM(balance), 0)::BIGINT AS total
FROM wallets
WHERE user_id = $1
`

func (q *Queries) GetWalletsTotalBalance(ctx context.Context, userID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getWalletsTotalBalance, userID)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const listWalletsByUser = `-- name: ListWalletsByUser :many
SELECT id, user_id, name, icon, balance, created_at
FROM wallets
WHERE user_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListWalletsByUser(ctx context.Context, userID pgtype.UUID) ([]Wallet, error) {
	rows, err := q.db.Query(ctx, listWalletsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Wallet
	for rows.Next() {
		var i Wallet
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Icon,
			&i.Balance,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const seedDefaultWallets = `-- name: SeedDefaultWallets :exec
INSERT INTO wallets (user_id, name, icon) VALUES
    ($1, 'Cash', '💵'),
    ($1, 'Bank', '🏦'),
    ($1, 'E-Wallet', '📱')
ON CONFLICT (user_id, name) DO NOTHING
`

func (q *Queries) SeedDefaultWallets(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, seedDefaultWallets, userID)
	return err
}

const updateWallet = `-- name: UpdateWallet :one
UPDATE wallets
SET name = $3, icon = $4
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, name, icon, balance, created_at
`

type UpdateWalletParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
	Name   string      `json:"name"`
	Icon   string      `json:"icon"`
}

func (q *Queries) UpdateWallet(ctx context.Context, arg UpdateWalletParams) (Wallet, error) {
	row := q.db.QueryRow(ctx, updateWallet,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.Icon,
	)
	var i Wallet
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Icon,
		&i.Balance,
		&i.CreatedAt,
	)
	return i, err
}

const updateWalletBalance = `-- name: UpdateWalletBalance :exec
UPDATE wallets
SET balance = balance + $2
WHERE id = $1
`

type UpdateWalletBalanceParams struct {
	ID      pgtype.UUID `json:"id"`
	Balance int64       `json:"balance"`
}

func (q *Queries) UpdateWalletBalance(ctx context.Context, arg UpdateWalletBalanceParams) error {
	_, err := q.db.Exec(ctx, updateWalletBalance, arg.ID, arg.Balance)
	return err
}
