// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package wallet

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countWalletsByUser = `-- name: CountWalletsByUser :one
SELECT COUNT(*)::BIGINT AS count FROM wallets WHERE user_id = $1
`

func (q *Queries) CountWalletsByUser(ctx context.Context, userID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countWalletsByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTransfer = `-- name: CreateTransfer :one
INSERT INTO transfers (user_id, from_wallet_id, to_wallet_id, amount, note)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, from_wallet_id, to_wallet_id, amount, note, created_at
`

type CreateTransferParams struct {
	UserID       pgtype.UUID `json:"user_id"`
	FromWalletID pgtype.UUID `json:"from_wallet_id"`
	ToWalletID   pgtype.UUID `json:"to_wallet_id"`
	Amount       int64       `json:"amount"`
	Note         string      `json:"note"`
}

func (q *Queries) CreateTransfer(ctx context.Context, arg CreateTransferParams) (Transfer, error) {
	row := q.db.QueryRow(ctx, createTransfer,
		arg.UserID,
		arg.FromWalletID,
		arg.ToWalletID,
		arg.Amount,
		arg.Note,
	)
	var i Transfer
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FromWalletID,
		&i.ToWalletID,
		&i.Amount,
		&i.Note,
		&i.CreatedAt,
	)
	return i, err
}

const createWallet = `-- name: CreateWallet :one
INSERT INTO wallets (user_id, name, icon)
VALUES ($1, $2, $3)
RETURNING id, user_id, name, icon, balance, created_at
`

type CreateWalletParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Name   string      `json:"name"`
	Icon   string      `json:"icon"`
}

func (q *Queries) CreateWallet(ctx context.Context, arg CreateWalletParams) (Wallet, error) {
	row := q.db.QueryRow(ctx, createWallet, arg.UserID, arg.Name, arg.Icon)
	var i Wallet
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Icon,
		&i.Balance,
		&i.CreatedAt,
	)
	return i, err
}

const deleteTransfer = `-- name: DeleteTransfer :one
DELETE FROM transfers
WHERE id = $1 AND user_id = $2
RETURNING from_wallet_id, to_wallet_id, amount
`

type DeleteTransferParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

type DeleteTransferRow struct {
	FromWalletID pgtype.UUID `json:"from_wallet_id"`
	ToWalletID   pgtype.UUID `json:"to_wallet_id"`
	Amount       int64       `json:"amount"`
}

func (q *Queries) DeleteTransfer(ctx context.Context, arg DeleteTransferParams) (DeleteTransferRow, error) {
	row := q.db.QueryRow(ctx, deleteTransfer, arg.ID, arg.UserID)
	var i DeleteTransferRow
	err := row.Scan(&i.FromWalletID, &i.ToWalletID, &i.Amount)
	return i, err
}

const deleteWallet = `-- name: DeleteWallet :exec
DELETE FROM wallets
WHERE id = $1 AND user_id = $2
`

type DeleteWalletParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) DeleteWallet(ctx context.Context, arg DeleteWalletParams) error {
	_, err := q.db.Exec(ctx, deleteWallet, arg.ID, arg.UserID)
	return err
}

const getWalletByID = `-- name: GetWalletByID :one
SELECT id, user_id, name, icon, balance, created_at
FROM wallets
WHERE id = $1 AND user_id = $2
`

type GetWalletByIDParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetWalletByID(ctx context.Context, arg GetWalletByIDParams) (Wallet, error) {
	row := q.db.QueryRow(ctx, getWalletByID, arg.ID, arg.UserID)
	var i Wallet
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Icon,
		&i.Balance,
		&i.CreatedAt,
	)
	return i, err
}

const getWalletsTotalBalance = `-- name: GetWalletsTotalBalance :one
SELECT COALESCE(SUM(balance), 0)::BIGINT AS total
FROM wallets
WHERE user_id = $1
`

func (q *Queries) GetWalletsTotalBalance(ctx context.Context, userID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getWalletsTotalBalance, userID)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const listTransfersByUser = `-- name: ListTransfersByUser :many
SELECT t.id, t.user_id, t.from_wallet_id, t.to_wallet_id, t.amount, t.note, t.created_at,
       fw.name AS from_wallet_name, fw.icon AS from_wallet_icon,
       tw.name AS to_wallet_name, tw.icon AS to_wallet_icon
FROM transfers t
JOIN wallets fw ON fw.id = t.from_wallet_id
JOIN wallets tw ON tw.id = t.to_wallet_id
WHERE t.user_id = $1
ORDER BY t.created_at DESC
LIMIT $2 OFFSET $3
`

type ListTransfersByUserParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

type ListTransfersByUserRow struct {
	ID             pgtype.UUID        `json:"id"`
	UserID         pgtype.UUID        `json:"user_id"`
	FromWalletID   pgtype.UUID        `json:"from_wallet_id"`
	ToWalletID     pgtype.UUID        `json:"to_wallet_id"`
	Amount         int64              `json:"amount"`
	Note           string             `json:"note"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	FromWalletName string             `json:"from_wallet_name"`
	FromWalletIcon string             `json:"from_wallet_icon"`
	ToWalletName   string             `json:"to_wallet_name"`
	ToWalletIcon   string             `json:"to_wallet_icon"`
}

func (q *Queries) ListTransfersByUser(ctx context.Context, arg ListTransfersByUserParams) ([]ListTransfersByUserRow, error) {
	rows, err := q.db.Query(ctx, listTransfersByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTransfersByUserRow
	for rows.Next() {
		var i ListTransfersByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.FromWalletID,
			&i.ToWalletID,
			&i.Amount,
			&i.Note,
			&i.CreatedAt,
			&i.FromWalletName,
			&i.FromWalletIcon,
			&i.ToWalletName,
			&i.ToWalletIcon,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWalletsByUser = `-- name: ListWalletsByUser :many
SELECT id, user_id, name, icon, balance, created_at
FROM wallets
WHERE user_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListWalletsByUser(ctx context.Context, userID pgtype.UUID) ([]Wallet, error) {
	rows, err := q.db.Query(ctx, listWalletsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Wallet
	for rows.Next() {
		var i Wallet
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Icon,
			&i.Balance,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const seedDefaultWallets = `-- name: SeedDefaultWallets :exec
INSERT INTO wallets (user_id, name, icon) VALUES
    ($1, 'Cash', '💵'),
    ($1, 'Bank', '🏦'),
    ($1, 'E-Wallet', '📱')
ON CONFLICT (user_id, name) DO NOTHING
`

func (q *Queries) SeedDefaultWallets(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, seedDefaultWallets, userID)
	return err
}

const setWalletBalance = `-- name: SetWalletBalance :exec
UPDATE wallets
SET balance = $3
WHERE id = $1 AND user_id = $2
`

type SetWalletBalanceParams struct {
	ID      pgtype.UUID `json:"id"`
	UserID  pgtype.UUID `json:"user_id"`
	Balance int64       `json:"balance"`
}

func (q *Queries) SetWalletBalance(ctx context.Context, arg SetWalletBalanceParams) error {
	_, err := q.db.Exec(ctx, setWalletBalance, arg.ID, arg.UserID, arg.Balance)
	return err
}

const updateWallet = `-- name: UpdateWallet :one
UPDATE wallets
SET name = $3, icon = $4
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, name, icon, balance, created_at
`

type UpdateWalletParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
	Name   string      `json:"name"`
	Icon   string      `json:"icon"`
}

func (q *Queries) UpdateWallet(ctx context.Context, arg UpdateWalletParams) (Wallet, error) {
	row := q.db.QueryRow(ctx, updateWallet,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.Icon,
	)
	var i Wallet
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Icon,
		&i.Balance,
		&i.CreatedAt,
	)
	return i, err
}

const updateWalletBalance = `-- name: UpdateWalletBalance :exec
UPDATE wallets
SET balance = balance + $2
WHERE id = $1
`

type UpdateWalletBalanceParams struct {
	ID      pgtype.UUID `json:"id"`
	Balance int64       `json:"balance"`
}

func (q *Queries) UpdateWalletBalance(ctx context.Context, arg UpdateWalletBalanceParams) error {
	_, err := q.db.Exec(ctx, updateWalletBalance, arg.ID, arg.Balance)
	return err
}
