// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package feedback

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countFeedbacks = `-- name: CountFeedbacks :one
SELECT COUNT(*) FROM feedbacks
`

func (q *Queries) CountFeedbacks(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countFeedbacks)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUserFeedbackToday = `-- name: CountUserFeedbackToday :one
SELECT COUNT(*) FROM feedbacks
WHERE user_id = $1
AND created_at >= CURRENT_DATE
`

func (q *Queries) CountUserFeedbackToday(ctx context.Context, userID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countUserFeedbackToday, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createFeedback = `-- name: CreateFeedback :one
INSERT INTO feedbacks (user_id, message, rating)
VALUES ($1, $2, $3)
RETURNING id, user_id, message, rating, created_at
`

type CreateFeedbackParams struct {
	UserID  pgtype.UUID `json:"user_id"`
	Message string      `json:"message"`
	Rating  pgtype.Int2 `json:"rating"`
}

func (q *Queries) CreateFeedback(ctx context.Context, arg CreateFeedbackParams) (Feedback, error) {
	row := q.db.QueryRow(ctx, createFeedback, arg.UserID, arg.Message, arg.Rating)
	var i Feedback
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Message,
		&i.Rating,
		&i.CreatedAt,
	)
	return i, err
}

const listFeedbacks = `-- name: ListFeedbacks :many
SELECT f.id, f.user_id, f.message, f.rating, f.created_at,
       u.name AS user_name, u.email AS user_email
FROM feedbacks f
JOIN users u ON u.id = f.user_id
ORDER BY f.created_at DESC
LIMIT $1 OFFSET $2
`

type ListFeedbacksParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListFeedbacksRow struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Message   string             `json:"message"`
	Rating    pgtype.Int2        `json:"rating"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UserName  string             `json:"user_name"`
	UserEmail string             `json:"user_email"`
}

func (q *Queries) ListFeedbacks(ctx context.Context, arg ListFeedbacksParams) ([]ListFeedbacksRow, error) {
	rows, err := q.db.Query(ctx, listFeedbacks, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFeedbacksRow
	for rows.Next() {
		var i ListFeedbacksRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Message,
			&i.Rating,
			&i.CreatedAt,
			&i.UserName,
			&i.UserEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
