// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package user

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Category struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Name      string             `json:"name"`
	Type      string             `json:"type"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Transaction struct {
	ID              pgtype.UUID        `json:"id"`
	UserID          pgtype.UUID        `json:"user_id"`
	Amount          int64              `json:"amount"`
	TransactionType string             `json:"transaction_type"`
	Description     pgtype.Text        `json:"description"`
	TransactionDate pgtype.Timestamptz `json:"transaction_date"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	Category        string             `json:"category"`
}

type User struct {
	ID           pgtype.UUID        `json:"id"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	TelegramID   pgtype.Int8        `json:"telegram_id"`
	Name         string             `json:"name"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}
