// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package user

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Budget struct {
	ID           pgtype.UUID        `json:"id"`
	UserID       pgtype.UUID        `json:"user_id"`
	CategoryName string             `json:"category_name"`
	Amount       int64              `json:"amount"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type Category struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Name      string             `json:"name"`
	Type      string             `json:"type"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Transaction struct {
	ID              pgtype.UUID        `json:"id"`
	UserID          pgtype.UUID        `json:"user_id"`
	Amount          int64              `json:"amount"`
	TransactionType string             `json:"transaction_type"`
	Description     pgtype.Text        `json:"description"`
	TransactionDate pgtype.Timestamptz `json:"transaction_date"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	Category        string             `json:"category"`
	WalletID        pgtype.UUID        `json:"wallet_id"`
}

type Transfer struct {
	ID           pgtype.UUID        `json:"id"`
	UserID       pgtype.UUID        `json:"user_id"`
	FromWalletID pgtype.UUID        `json:"from_wallet_id"`
	ToWalletID   pgtype.UUID        `json:"to_wallet_id"`
	Amount       int64              `json:"amount"`
	Note         string             `json:"note"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID           pgtype.UUID        `json:"id"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	TelegramID   pgtype.Int8        `json:"telegram_id"`
	Name         string             `json:"name"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type Wallet struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Name      string             `json:"name"`
	Icon      string             `json:"icon"`
	Balance   int64              `json:"balance"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}
