// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package user

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, password_hash, name)
VALUES ($1, $2, $3)
RETURNING id, email, name, telegram_id, created_at
`

type CreateUserParams struct {
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
	Name         string `json:"name"`
}

type CreateUserRow struct {
	ID         pgtype.UUID        `json:"id"`
	Email      string             `json:"email"`
	Name       string             `json:"name"`
	TelegramID pgtype.Int8        `json:"telegram_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.PasswordHash, arg.Name)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.TelegramID,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, name, telegram_id, created_at
FROM users
WHERE email = $1
`

type GetUserByEmailRow struct {
	ID           pgtype.UUID        `json:"id"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	Name         string             `json:"name"`
	TelegramID   pgtype.Int8        `json:"telegram_id"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.TelegramID,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, name, telegram_id, created_at
FROM users
WHERE id = $1
`

type GetUserByIDRow struct {
	ID         pgtype.UUID        `json:"id"`
	Email      string             `json:"email"`
	Name       string             `json:"name"`
	TelegramID pgtype.Int8        `json:"telegram_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.TelegramID,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByTelegramID = `-- name: GetUserByTelegramID :one
SELECT id, email, name, telegram_id, created_at
FROM users
WHERE telegram_id = $1
`

type GetUserByTelegramIDRow struct {
	ID         pgtype.UUID        `json:"id"`
	Email      string             `json:"email"`
	Name       string             `json:"name"`
	TelegramID pgtype.Int8        `json:"telegram_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetUserByTelegramID(ctx context.Context, telegramID pgtype.Int8) (GetUserByTelegramIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByTelegramID, telegramID)
	var i GetUserByTelegramIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.TelegramID,
		&i.CreatedAt,
	)
	return i, err
}

const linkTelegram = `-- name: LinkTelegram :one
UPDATE users
SET telegram_id = $2
WHERE id = $1
RETURNING id, email, name, telegram_id, created_at
`

type LinkTelegramParams struct {
	ID         pgtype.UUID `json:"id"`
	TelegramID pgtype.Int8 `json:"telegram_id"`
}

type LinkTelegramRow struct {
	ID         pgtype.UUID        `json:"id"`
	Email      string             `json:"email"`
	Name       string             `json:"name"`
	TelegramID pgtype.Int8        `json:"telegram_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) LinkTelegram(ctx context.Context, arg LinkTelegramParams) (LinkTelegramRow, error) {
	row := q.db.QueryRow(ctx, linkTelegram, arg.ID, arg.TelegramID)
	var i LinkTelegramRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.TelegramID,
		&i.CreatedAt,
	)
	return i, err
}

const listLinkedTelegramUsers = `-- name: ListLinkedTelegramUsers :many
SELECT id, email, name, telegram_id, created_at
FROM users
WHERE telegram_id IS NOT NULL
`

type ListLinkedTelegramUsersRow struct {
	ID         pgtype.UUID        `json:"id"`
	Email      string             `json:"email"`
	Name       string             `json:"name"`
	TelegramID pgtype.Int8        `json:"telegram_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListLinkedTelegramUsers(ctx context.Context) ([]ListLinkedTelegramUsersRow, error) {
	rows, err := q.db.Query(ctx, listLinkedTelegramUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLinkedTelegramUsersRow
	for rows.Next() {
		var i ListLinkedTelegramUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.TelegramID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unlinkTelegram = `-- name: UnlinkTelegram :one
UPDATE users
SET telegram_id = NULL
WHERE id = $1
RETURNING id, email, name, telegram_id, created_at
`

type UnlinkTelegramRow struct {
	ID         pgtype.UUID        `json:"id"`
	Email      string             `json:"email"`
	Name       string             `json:"name"`
	TelegramID pgtype.Int8        `json:"telegram_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) UnlinkTelegram(ctx context.Context, id pgtype.UUID) (UnlinkTelegramRow, error) {
	row := q.db.QueryRow(ctx, unlinkTelegram, id)
	var i UnlinkTelegramRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.TelegramID,
		&i.CreatedAt,
	)
	return i, err
}

const updatePassword = `-- name: UpdatePassword :exec
UPDATE users
SET password_hash = $2
WHERE id = $1
`

type UpdatePasswordParams struct {
	ID           pgtype.UUID `json:"id"`
	PasswordHash string      `json:"password_hash"`
}

func (q *Queries) UpdatePassword(ctx context.Context, arg UpdatePasswordParams) error {
	_, err := q.db.Exec(ctx, updatePassword, arg.ID, arg.PasswordHash)
	return err
}

const updateProfile = `-- name: UpdateProfile :one
UPDATE users
SET name = $2, email = $3
WHERE id = $1
RETURNING id, email, name, telegram_id, created_at
`

type UpdateProfileParams struct {
	ID    pgtype.UUID `json:"id"`
	Name  string      `json:"name"`
	Email string      `json:"email"`
}

type UpdateProfileRow struct {
	ID         pgtype.UUID        `json:"id"`
	Email      string             `json:"email"`
	Name       string             `json:"name"`
	TelegramID pgtype.Int8        `json:"telegram_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) UpdateProfile(ctx context.Context, arg UpdateProfileParams) (UpdateProfileRow, error) {
	row := q.db.QueryRow(ctx, updateProfile, arg.ID, arg.Name, arg.Email)
	var i UpdateProfileRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.TelegramID,
		&i.CreatedAt,
	)
	return i, err
}
