// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package analytics

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countFeatureUsageToday = `-- name: CountFeatureUsageToday :one
SELECT COUNT(*)::BIGINT AS count
FROM feature_usage
WHERE user_id = $1 AND feature = $2 AND used_at = CURRENT_DATE
`

type CountFeatureUsageTodayParams struct {
	UserID  pgtype.UUID `json:"user_id"`
	Feature string      `json:"feature"`
}

func (q *Queries) CountFeatureUsageToday(ctx context.Context, arg CountFeatureUsageTodayParams) (int64, error) {
	row := q.db.QueryRow(ctx, countFeatureUsageToday, arg.UserID, arg.Feature)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getCategoryBreakdown = `-- name: GetCategoryBreakdown :many
SELECT
  category,
  transaction_type,
  COALESCE(SUM(amount), 0)::BIGINT AS total,
  COUNT(*)::BIGINT AS count
FROM transactions
WHERE user_id = $1
  AND transaction_date >= $2
  AND transaction_date < $3
GROUP BY category, transaction_type
ORDER BY total DESC
`

type GetCategoryBreakdownParams struct {
	UserID            pgtype.UUID        `json:"user_id"`
	TransactionDate   pgtype.Timestamptz `json:"transaction_date"`
	TransactionDate_2 pgtype.Timestamptz `json:"transaction_date_2"`
}

type GetCategoryBreakdownRow struct {
	Category        string `json:"category"`
	TransactionType string `json:"transaction_type"`
	Total           int64  `json:"total"`
	Count           int64  `json:"count"`
}

func (q *Queries) GetCategoryBreakdown(ctx context.Context, arg GetCategoryBreakdownParams) ([]GetCategoryBreakdownRow, error) {
	rows, err := q.db.Query(ctx, getCategoryBreakdown, arg.UserID, arg.TransactionDate, arg.TransactionDate_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCategoryBreakdownRow
	for rows.Next() {
		var i GetCategoryBreakdownRow
		if err := rows.Scan(
			&i.Category,
			&i.TransactionType,
			&i.Total,
			&i.Count,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDailyBreakdown = `-- name: GetDailyBreakdown :many
SELECT
  DATE(transaction_date AT TIME ZONE 'Asia/Jakarta') AS tx_date,
  transaction_type,
  COALESCE(SUM(amount), 0)::BIGINT AS total
FROM transactions
WHERE user_id = $1
  AND transaction_date >= $2
  AND transaction_date < $3
GROUP BY tx_date, transaction_type
ORDER BY tx_date ASC
`

type GetDailyBreakdownParams struct {
	UserID            pgtype.UUID        `json:"user_id"`
	TransactionDate   pgtype.Timestamptz `json:"transaction_date"`
	TransactionDate_2 pgtype.Timestamptz `json:"transaction_date_2"`
}

type GetDailyBreakdownRow struct {
	TxDate          pgtype.Date `json:"tx_date"`
	TransactionType string      `json:"transaction_type"`
	Total           int64       `json:"total"`
}

func (q *Queries) GetDailyBreakdown(ctx context.Context, arg GetDailyBreakdownParams) ([]GetDailyBreakdownRow, error) {
	rows, err := q.db.Query(ctx, getDailyBreakdown, arg.UserID, arg.TransactionDate, arg.TransactionDate_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDailyBreakdownRow
	for rows.Next() {
		var i GetDailyBreakdownRow
		if err := rows.Scan(&i.TxDate, &i.TransactionType, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMonthlySummary = `-- name: GetMonthlySummary :many
SELECT transaction_type, COALESCE(SUM(amount), 0)::BIGINT AS total
FROM transactions
WHERE user_id = $1
  AND transaction_date >= $2
  AND transaction_date < $3
GROUP BY transaction_type
`

type GetMonthlySummaryParams struct {
	UserID            pgtype.UUID        `json:"user_id"`
	TransactionDate   pgtype.Timestamptz `json:"transaction_date"`
	TransactionDate_2 pgtype.Timestamptz `json:"transaction_date_2"`
}

type GetMonthlySummaryRow struct {
	TransactionType string `json:"transaction_type"`
	Total           int64  `json:"total"`
}

func (q *Queries) GetMonthlySummary(ctx context.Context, arg GetMonthlySummaryParams) ([]GetMonthlySummaryRow, error) {
	rows, err := q.db.Query(ctx, getMonthlySummary, arg.UserID, arg.TransactionDate, arg.TransactionDate_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMonthlySummaryRow
	for rows.Next() {
		var i GetMonthlySummaryRow
		if err := rows.Scan(&i.TransactionType, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMonthlyTrend = `-- name: GetMonthlyTrend :many
SELECT
  TO_CHAR(DATE_TRUNC('month', transaction_date AT TIME ZONE 'Asia/Jakarta'), 'YYYY-MM') AS tx_month,
  transaction_type,
  COALESCE(SUM(amount), 0)::BIGINT AS total
FROM transactions
WHERE user_id = $1
  AND transaction_date >= $2
  AND transaction_date < $3
GROUP BY tx_month, transaction_type
ORDER BY tx_month ASC
`

type GetMonthlyTrendParams struct {
	UserID            pgtype.UUID        `json:"user_id"`
	TransactionDate   pgtype.Timestamptz `json:"transaction_date"`
	TransactionDate_2 pgtype.Timestamptz `json:"transaction_date_2"`
}

type GetMonthlyTrendRow struct {
	TxMonth         string `json:"tx_month"`
	TransactionType string `json:"transaction_type"`
	Total           int64  `json:"total"`
}

func (q *Queries) GetMonthlyTrend(ctx context.Context, arg GetMonthlyTrendParams) ([]GetMonthlyTrendRow, error) {
	rows, err := q.db.Query(ctx, getMonthlyTrend, arg.UserID, arg.TransactionDate, arg.TransactionDate_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMonthlyTrendRow
	for rows.Next() {
		var i GetMonthlyTrendRow
		if err := rows.Scan(&i.TxMonth, &i.TransactionType, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRoastCache = `-- name: GetRoastCache :one
SELECT roast_text FROM roast_cache
WHERE user_id = $1 AND year = $2 AND month = $3
`

type GetRoastCacheParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Year   int32       `json:"year"`
	Month  int32       `json:"month"`
}

func (q *Queries) GetRoastCache(ctx context.Context, arg GetRoastCacheParams) (string, error) {
	row := q.db.QueryRow(ctx, getRoastCache, arg.UserID, arg.Year, arg.Month)
	var roast_text string
	err := row.Scan(&roast_text)
	return roast_text, err
}

const getTopDescriptions = `-- name: GetTopDescriptions :many
SELECT
  description,
  COUNT(*)::BIGINT AS frequency,
  COALESCE(SUM(amount), 0)::BIGINT AS total_amount
FROM transactions
WHERE user_id = $1
  AND transaction_type = $2
  AND transaction_date >= $3
  AND transaction_date < $4
  AND description IS NOT NULL
  AND description != ''
GROUP BY description
ORDER BY total_amount DESC
LIMIT $5
`

type GetTopDescriptionsParams struct {
	UserID            pgtype.UUID        `json:"user_id"`
	TransactionType   string             `json:"transaction_type"`
	TransactionDate   pgtype.Timestamptz `json:"transaction_date"`
	TransactionDate_2 pgtype.Timestamptz `json:"transaction_date_2"`
	Limit             int32              `json:"limit"`
}

type GetTopDescriptionsRow struct {
	Description pgtype.Text `json:"description"`
	Frequency   int64       `json:"frequency"`
	TotalAmount int64       `json:"total_amount"`
}

func (q *Queries) GetTopDescriptions(ctx context.Context, arg GetTopDescriptionsParams) ([]GetTopDescriptionsRow, error) {
	rows, err := q.db.Query(ctx, getTopDescriptions,
		arg.UserID,
		arg.TransactionType,
		arg.TransactionDate,
		arg.TransactionDate_2,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTopDescriptionsRow
	for rows.Next() {
		var i GetTopDescriptionsRow
		if err := rows.Scan(&i.Description, &i.Frequency, &i.TotalAmount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertFeatureUsage = `-- name: InsertFeatureUsage :exec
INSERT INTO feature_usage (user_id, feature) VALUES ($1, $2)
`

type InsertFeatureUsageParams struct {
	UserID  pgtype.UUID `json:"user_id"`
	Feature string      `json:"feature"`
}

func (q *Queries) InsertFeatureUsage(ctx context.Context, arg InsertFeatureUsageParams) error {
	_, err := q.db.Exec(ctx, insertFeatureUsage, arg.UserID, arg.Feature)
	return err
}

const upsertRoastCache = `-- name: UpsertRoastCache :exec
INSERT INTO roast_cache (user_id, year, month, roast_text)
VALUES ($1, $2, $3, $4)
ON CONFLICT (user_id, year, month)
DO UPDATE SET roast_text = EXCLUDED.roast_text, created_at = NOW()
`

type UpsertRoastCacheParams struct {
	UserID    pgtype.UUID `json:"user_id"`
	Year      int32       `json:"year"`
	Month     int32       `json:"month"`
	RoastText string      `json:"roast_text"`
}

func (q *Queries) UpsertRoastCache(ctx context.Context, arg UpsertRoastCacheParams) error {
	_, err := q.db.Exec(ctx, upsertRoastCache,
		arg.UserID,
		arg.Year,
		arg.Month,
		arg.RoastText,
	)
	return err
}
