// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package goal

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addToGoal = `-- name: AddToGoal :one
UPDATE goals
SET current_amount = current_amount + $3
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, name, target_amount, current_amount, deadline, created_at
`

type AddToGoalParams struct {
	ID            pgtype.UUID `json:"id"`
	UserID        pgtype.UUID `json:"user_id"`
	CurrentAmount int64       `json:"current_amount"`
}

func (q *Queries) AddToGoal(ctx context.Context, arg AddToGoalParams) (Goal, error) {
	row := q.db.QueryRow(ctx, addToGoal, arg.ID, arg.UserID, arg.CurrentAmount)
	var i Goal
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.TargetAmount,
		&i.CurrentAmount,
		&i.Deadline,
		&i.CreatedAt,
	)
	return i, err
}

const createGoal = `-- name: CreateGoal :one
INSERT INTO goals (user_id, name, target_amount, current_amount, deadline)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, name, target_amount, current_amount, deadline, created_at
`

type CreateGoalParams struct {
	UserID        pgtype.UUID `json:"user_id"`
	Name          string      `json:"name"`
	TargetAmount  int64       `json:"target_amount"`
	CurrentAmount int64       `json:"current_amount"`
	Deadline      pgtype.Date `json:"deadline"`
}

func (q *Queries) CreateGoal(ctx context.Context, arg CreateGoalParams) (Goal, error) {
	row := q.db.QueryRow(ctx, createGoal,
		arg.UserID,
		arg.Name,
		arg.TargetAmount,
		arg.CurrentAmount,
		arg.Deadline,
	)
	var i Goal
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.TargetAmount,
		&i.CurrentAmount,
		&i.Deadline,
		&i.CreatedAt,
	)
	return i, err
}

const deleteGoal = `-- name: DeleteGoal :exec
DELETE FROM goals
WHERE id = $1 AND user_id = $2
`

type DeleteGoalParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) DeleteGoal(ctx context.Context, arg DeleteGoalParams) error {
	_, err := q.db.Exec(ctx, deleteGoal, arg.ID, arg.UserID)
	return err
}

const listGoalsByUser = `-- name: ListGoalsByUser :many
SELECT id, user_id, name, target_amount, current_amount, deadline, created_at
FROM goals
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListGoalsByUser(ctx context.Context, userID pgtype.UUID) ([]Goal, error) {
	rows, err := q.db.Query(ctx, listGoalsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Goal
	for rows.Next() {
		var i Goal
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.TargetAmount,
			&i.CurrentAmount,
			&i.Deadline,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateGoal = `-- name: UpdateGoal :one
UPDATE goals
SET name = $3, target_amount = $4, deadline = $5
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, name, target_amount, current_amount, deadline, created_at
`

type UpdateGoalParams struct {
	ID           pgtype.UUID `json:"id"`
	UserID       pgtype.UUID `json:"user_id"`
	Name         string      `json:"name"`
	TargetAmount int64       `json:"target_amount"`
	Deadline     pgtype.Date `json:"deadline"`
}

func (q *Queries) UpdateGoal(ctx context.Context, arg UpdateGoalParams) (Goal, error) {
	row := q.db.QueryRow(ctx, updateGoal,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.TargetAmount,
		arg.Deadline,
	)
	var i Goal
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.TargetAmount,
		&i.CurrentAmount,
		&i.Deadline,
		&i.CreatedAt,
	)
	return i, err
}
